/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OfficerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.OfficerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRegistration;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ManagerRole.RefugeeDetailPanel;

/**
 *
 * @author hp
 */
public class OfficerWorkAreaPanel extends javax.swing.JPanel {
     
     private JPanel userProcessContainer;
    private OfficerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    /**
     * Creates new form OfficerWorkAreaPanel
     */
    
    
     public OfficerWorkAreaPanel(JPanel userProcessContainer, UserAccount account, OfficerOrganization organization, Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem=business;
        this.network=network;
        populateRequestTable();
    }
     
       public void populateRequestTable(){
           
            DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        
        model.setRowCount(0);
        int x=0;
        
                     for (WorkRegistration register : this.organization.getWorkQueue().getRegistrationList()){
                         if(register.getOfficer()==null || register.getOfficer()==this.userAccount){
                         Object[] row = new Object[4]; x++;
                         row[0] = x;
                         row[1]= register;
                         row[2] =register.getCountry();
                         row[3] = register.getStatus();
                         
                         model.addRow(row);
                         }
                     }
                 

           
           
       
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_Approval = new javax.swing.JButton();
        Button_Declined = new javax.swing.JButton();
        Button_received = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Button_sedetail = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        Button_Approval.setBackground(new java.awt.Color(51, 153, 255));
        Button_Approval.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Approval.setText("Approve");
        Button_Approval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ApprovalActionPerformed(evt);
            }
        });

        Button_Declined.setBackground(new java.awt.Color(51, 153, 255));
        Button_Declined.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Declined.setText("Decline");
        Button_Declined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeclinedActionPerformed(evt);
            }
        });

        Button_received.setBackground(new java.awt.Color(51, 153, 255));
        Button_received.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_received.setText("Receive");
        Button_received.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_receivedActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sno", "RefugeeId", "Migrationcountry", "status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Button_sedetail.setBackground(new java.awt.Color(51, 153, 255));
        Button_sedetail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_sedetail.setText("See Details");
        Button_sedetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sedetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_received, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(Button_sedetail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(Button_Declined, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(Button_Approval, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Declined)
                    .addComponent(Button_received)
                    .addComponent(Button_Approval)
                    .addComponent(Button_sedetail))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Welcome To Officer Work Area ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ApprovalActionPerformed
        // TODO add your handling code here:
        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {

            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            if(wr.getOfficer()==null)
             {
                 JOptionPane.showMessageDialog(null,"job Didnt assigned yet"); return;
             }
            if(!wr.getStatus().equals("received at country")){ JOptionPane.showMessageDialog(null,"Already done"); return;}
            wr.setStatus("approved");
            JOptionPane.showMessageDialog(null,"Immigration approved");
            this.populateRequestTable();
        }else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_ApprovalActionPerformed

    private void Button_receivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_receivedActionPerformed
        // TODO add your handling code here:
        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {

            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            if(!wr.getStatus().equals("sent to country")){ JOptionPane.showMessageDialog(null,"Already Recieved"); return;}
            wr.setStatus("received at country");
            wr.setOfficer(this.userAccount);
            JOptionPane.showMessageDialog(null,"job assigned");
            this.populateRequestTable();
        }else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_receivedActionPerformed

    private void Button_DeclinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeclinedActionPerformed
        // TODO add your handling code here:
        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {

            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            if(wr.getOfficer()==null)
             {
                 JOptionPane.showMessageDialog(null,"job Didnt assigned yet"); return;
             }
            if(!wr.getStatus().equals("received at country")){ JOptionPane.showMessageDialog(null,"Already done"); return;}
            wr.setStatus("declined");
            JOptionPane.showMessageDialog(null,"Immigration declined");
            
            this.populateRequestTable();
        }else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_DeclinedActionPerformed

    private void Button_sedetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sedetailActionPerformed
        // TODO add your handling code here:
        
        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {
            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            RefugeeDetailPanel refufeedetail = new RefugeeDetailPanel(userProcessContainer, userAccount, enterprise, network, wr);
            userProcessContainer.add("refufeedetail", refufeedetail);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_sedetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Approval;
    private javax.swing.JButton Button_Declined;
    private javax.swing.JButton Button_received;
    private javax.swing.JButton Button_sedetail;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
