/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RegisterationRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.WorkQueue.WorkRegistration;
import Business.WorkQueue.refugeedetails;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author hp
 */
public class NewRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewRegisterJPanel
     */
    ButtonGroup buttonGroup = new ButtonGroup();
    
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    private String imagepath;
    public NewRegisterJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem ecosystem, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem=ecosystem;
        this.network=network;
         buttonGroup.add(this.Radio_Female);
        buttonGroup.add(this.Radio_Male);
        
        this.label_image.setIcon(ResizeImage( new File("Image\\output.jpg").getAbsolutePath()));
        
        for (Network net : this.ecosystem.getNetworkList())
        {
            if(net!=this.network)
            this.Combo_Country.addItem(net.getName());
        }
            
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_Back = new javax.swing.JButton();
        Button_submit = new javax.swing.JButton();
        Label_country = new javax.swing.JLabel();
        Combo_Country = new javax.swing.JComboBox();
        Label_Gender = new javax.swing.JLabel();
        Radio_Male = new javax.swing.JRadioButton();
        Radio_Female = new javax.swing.JRadioButton();
        Labe_Age = new javax.swing.JLabel();
        Text_Age = new javax.swing.JTextField();
        Label_name = new javax.swing.JLabel();
        Text_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fathernam = new javax.swing.JTextField();
        mothername = new javax.swing.JTextField();
        child = new javax.swing.JTextField();
        error_age = new javax.swing.JLabel();
        error_name = new javax.swing.JLabel();
        error_mc = new javax.swing.JLabel();
        error_gender = new javax.swing.JLabel();
        error_mname = new javax.swing.JLabel();
        error_nc = new javax.swing.JLabel();
        error_fname = new javax.swing.JLabel();
        label_image = new javax.swing.JLabel();
        upload_imgae = new javax.swing.JButton();
        error_image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        Button_Back.setBackground(new java.awt.Color(51, 153, 255));
        Button_Back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Back.setText("<<  Back");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        Button_submit.setBackground(new java.awt.Color(51, 153, 255));
        Button_submit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_submit.setText("Submit");
        Button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_submitActionPerformed(evt);
            }
        });

        Label_country.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_country.setText("Migration Country");

        Combo_Country.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Label_Gender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Gender.setText("Gender");

        Radio_Male.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Radio_Male.setText("Male");

        Radio_Female.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Radio_Female.setText("Female");

        Labe_Age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Labe_Age.setText("Age");

        Text_Age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Label_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_name.setText("Name");

        Text_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Text_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DETAILS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Father's Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Mother's Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("No of Child");

        fathernam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        mothername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        child.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        error_age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_age.setForeground(new java.awt.Color(255, 51, 51));

        error_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_name.setForeground(new java.awt.Color(255, 51, 51));

        error_mc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_mc.setForeground(new java.awt.Color(255, 51, 51));

        error_gender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_gender.setForeground(new java.awt.Color(255, 51, 51));

        error_mname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_mname.setForeground(new java.awt.Color(255, 51, 51));

        error_nc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_nc.setForeground(new java.awt.Color(255, 51, 51));

        error_fname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_fname.setForeground(new java.awt.Color(255, 51, 51));

        label_image.setText("image");

        upload_imgae.setBackground(new java.awt.Color(51, 153, 255));
        upload_imgae.setText("Upload Image");
        upload_imgae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_imgaeActionPerformed(evt);
            }
        });

        error_image.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_image.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Labe_Age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Label_Gender, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(Label_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Radio_Male)
                                                .addGap(18, 18, 18)
                                                .addComponent(Radio_Female))
                                            .addComponent(Text_Age)
                                            .addComponent(Text_Name)
                                            .addComponent(Combo_Country, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fathernam)
                                            .addComponent(mothername)
                                            .addComponent(child)))
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(error_nc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(error_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(error_age, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(error_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(error_fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(error_mc, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(error_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(Label_country, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(error_image, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upload_imgae))))
                        .addGap(126, 126, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(Button_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Label_name)
                                .addComponent(Text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_age, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Labe_Age)
                                .addComponent(Text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Label_Gender)
                                .addComponent(Radio_Male)
                                .addComponent(Radio_Female)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_mc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Label_country)
                                .addComponent(Combo_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fathernam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mothername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(child, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(error_nc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_submit)
                            .addComponent(Button_Back)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(upload_imgae)
                        .addGap(39, 39, 39)
                        .addComponent(error_image, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(178, 178, 178))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Welcome To New Registarion Work Area ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel4)
                .addContainerGap(799, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validatefields()
    {
        boolean bname=true , bfname=true, bmname=true, bage=true, bgender=true, bnoc=true, bmc= true, bimage=true;
        
        if(this.imagepath==null){bimage=false; this.error_image.setText("plz select image");}
        else{this.error_image.setText("");}
        
        String regex="\\d+";
        //
        if(this.Combo_Country.getSelectedItem()==null) {this.error_mc.setText("plz select"); bmc=false;}
        else this.error_mc.setText("");
        //
        if(this.Text_Name.getText().isEmpty())
        {
            this.error_name.setText("Plz Enter Text"); bname=false;
        }
        else if(Text_Name.getText().matches(regex))
                {
                    error_name.setText("can't be a number"); bname=false;
                }
        else if(!Text_Name.getText().matches("^[a-zA-Z0-9]{4,30}$"))
        {
            error_name.setText("No spcl char & min length 4"); bname=false;
        }
        else this.error_name.setText("");
        //
        try
                {
                error_age.setText("");
                Integer.parseInt(this.Text_Age.getText());
                
                }
                catch(NumberFormatException e)
                {
                if(this.Text_Age.getText().isEmpty()) this.error_age.setText("can not be empty");   
                else
                error_age.setText("enter valid number");
                bage=false;
                }
        //
        if(this.fathernam.getText().isEmpty())
        {
            this.error_fname.setText("Plz Enter Text"); bfname=false;
        }
        else if(fathernam.getText().matches(regex))
                {
                    error_fname.setText("can't be a number"); bfname=false;
                }
        else if(!fathernam.getText().matches("^[a-zA-Z0-9]{4,30}$"))
        {
            error_fname.setText("No spcl char & min length 4"); bfname=false;
        }
        else this.error_fname.setText("");
        //
        if(this.mothername.getText().isEmpty())
        {
            this.error_mname.setText("Plz Enter Text"); bmname=false;
        }
        else if(mothername.getText().matches(regex))
                {
                    error_mname.setText("can't be a number"); bmname=false;
                }
        else if(!mothername.getText().matches("^[a-zA-Z0-9]{4,30}$"))
        {
            error_mname.setText("No spcl char & min length 4"); bmname=false;
        }
        else this.error_mname.setText("");
        //
        try
                {
                    error_nc.setText("");
                Integer.parseInt(this.child.getText());
                }
                catch(NumberFormatException e)
                {
                if(child.getText().isEmpty()) this.error_nc.setText("can not be empty");   
                else
                error_nc.setText("enter valid number");
                bmc=false;
                }
        if(!this.Radio_Female.isSelected() && !this.Radio_Male.isSelected()) {this.error_gender.setText("select one"); bage=false;}
        else this.error_gender.setText("");
        if(!bname || !bage || !bfname || !bmname || !bmc|| !bnoc || !bgender || !bimage) return false;
        return true;
    }
    private void Button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_submitActionPerformed
        // TODO add your handling code here:
        
        
        if(this.validatefields()==false) return;
        
        UUID idOne = UUID.randomUUID();
        WorkRegistration wr = new WorkRegistration();
        wr.setCountry(this.Combo_Country.getSelectedItem().toString());
        wr.setUnoregister(this.userAccount);
        wr.setRefugeeid(idOne);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ManagerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getRegistrationList().add(wr);
            userAccount.getWorkQueue().getRegistrationList().add(wr);
            JOptionPane.showMessageDialog(null,"Registered ");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"There is no manager org ");
        }
        
        refugeedetails rd = new refugeedetails();
        rd.setAge(Integer.parseInt(this.Text_Age.getText()));
        rd.setChildno(Integer.parseInt(this.child.getText()));
        rd.setCountry(this.network.getName());
        rd.setFathername(this.fathernam.getText());
        if(this.Radio_Male.isSelected()) rd.setGender("Male");
        if(this.Radio_Female.isSelected()) rd.setGender("Female");
        rd.setMothername(this.mothername.getText());
        rd.setName(this.Text_Name.getText());
        rd.setRefugeeid("sjdjgfdf");
        
        double x=Math.random();
        wr.setFilename(x+this.Text_Name.getText()+".ser");
        wr.setImage_path(x+this.Text_Name.getText()+".jpg");
        
        
        try {
         FileOutputStream fileOut =
         new FileOutputStream("Rfiles/"+x+this.Text_Name.getText()+".ser" );
         ObjectOutputStream out = new ObjectOutputStream(fileOut);
         out.writeObject(rd);
         out.close();
         fileOut.close();
         System.out.printf("Serialized data is saved in /tmp/employee.ser");
      } catch (IOException i) {
         i.printStackTrace();
      }
        
        BufferedImage image = null;
        File f = null;
        

    //read image
    try{
      f = new File(this.imagepath); //image file path
      image = new BufferedImage(this.label_image.getWidth(), this.label_image.getHeight(), BufferedImage.TYPE_INT_ARGB);
      image = ImageIO.read(f);
      System.out.println("Reading complete.");
    }catch(IOException e){
      System.out.println("Error: "+e);
    }
        
        try{
      f = new File("Image//"+x+this.Text_Name.getText()+".jpg");  //output file path
      ImageIO.write(image, "jpg", f);
      System.out.println("Writing complete.");
    }catch(IOException e){
      System.out.println("Error: "+e);
    }
       // this.userAccount.getWorkQueue().getRegistrationList().add(wr);
       
       this.Text_Age.setText("");
       this.Text_Name.setText("");
       this.fathernam.setText("");
       this.child.setText("");
       this.mothername.setText("");
       this.imagepath=null;
       
        
    }//GEN-LAST:event_Button_submitActionPerformed

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RegisterWorkAreaPanel dwjp = (RegisterWorkAreaPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_Button_BackActionPerformed

    private void Text_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NameActionPerformed

    public ImageIcon ResizeImage(String Imagepath)
    {
        ImageIcon Myimage = new ImageIcon(Imagepath);
        Image img = Myimage.getImage();
        Image newimg = img.getScaledInstance(249, 258,Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newimg);
        System.out.println(Imagepath);
        return image;
        
        
    }
    
    
    
    private void upload_imgaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_imgaeActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new  FileNameExtensionFilter("*.Images", "jpg" , "png", "gif");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            this.imagepath = selectedFile.getAbsolutePath();
            //System.out.println(this.imagepath);
            this.label_image.setIcon(ResizeImage(imagepath));
        }
        else if(result== JFileChooser.CANCEL_OPTION)
            System.out.println("NO File Selected");
        
        
                
    }//GEN-LAST:event_upload_imgaeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_submit;
    private javax.swing.JComboBox Combo_Country;
    private javax.swing.JLabel Labe_Age;
    private javax.swing.JLabel Label_Gender;
    private javax.swing.JLabel Label_country;
    private javax.swing.JLabel Label_name;
    private javax.swing.JRadioButton Radio_Female;
    private javax.swing.JRadioButton Radio_Male;
    private javax.swing.JTextField Text_Age;
    private javax.swing.JTextField Text_Name;
    private javax.swing.JTextField child;
    private javax.swing.JLabel error_age;
    private javax.swing.JLabel error_fname;
    private javax.swing.JLabel error_gender;
    private javax.swing.JLabel error_image;
    private javax.swing.JLabel error_mc;
    private javax.swing.JLabel error_mname;
    private javax.swing.JLabel error_name;
    private javax.swing.JLabel error_nc;
    private javax.swing.JTextField fathernam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_image;
    private javax.swing.JTextField mothername;
    private javax.swing.JButton upload_imgae;
    // End of variables declaration//GEN-END:variables
}
